drop table users cascade;
drop table contacts cascade;

CREATE TABLE users(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL
);

CREATE TABLE contacts(

    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telephone varchar(100),
    email varchar(100) ,
    user_id integer REFERENCES users(id)
);

